version: "3.9"
services:
  angular:
    build:
      context: ./../..
      dockerfile: ./docker/dev/front-dev/Dockerfile
    container_name: angular
    ports:
      - "80:4200"
    volumes:
      - ./../../frontend:/sigl
    restart: always

  db:
    image: postgres
    volumes:
      - ./../../database/data/db:/var/lib/postgresql/data
    command: -p 5433
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build:
      context: ./../..
      dockerfile: ./docker/dev/back-dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./../../backend:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db

  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - dbsonar
    environment:
      - SONAR_JBDC_URL=jdbc:postgresql://dbsonar:5432/sonar
      - SONAR_JBDC_USERNAME=sonar
      - SONAR_JBDC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  dbsonar:
    image: postgres:12
    hostname: postgresql
    container_name: postgresql
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  sonarscanner:
    build:
      context: ./../..
      dockerfile: ./docker/dev/sonarscanner/Dockerfile
    container_name: sonarscanner

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data: