---
stages:
  - lint
  - build
  - deploy

variables:
  REGISTRY: $CI_REGISTRY/$CI_PROJECT_ROOT_NAMESPACE/$CI_PROJECT_NAME

.install-node-modules: &install-node-modules
  image:
    name: $REGISTRY/dev-angular
    entrypoint: [""]
  before_script:
    - cd frontend
    - npm install

lint-angular:
  stage: lint
  <<: *install-node-modules
  script:
    - npm run lint
  allow_failure: true

lint-django:
  stage: lint
  image:
    name: $REGISTRY/dev-django
    entrypoint: [""]
  before_script:
    - cd backend
  script:
    - pylint *
  allow_failure: true

build-angular:
  stage: build
  needs: ["lint-angular"]
  <<: *install-node-modules
  script:
    - npm run build
