# Generated by Django 4.1.1 on 2022-10-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherincharge',
            name='formationCenter',
        ),
        migrations.AddField(
            model_name='formationcenter',
            name='teacherInCharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FormationCenter', to='base.teacherincharge'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='base.mentor'),
        ),
    ]
