# Generated by Django 4.1.2 on 2022-10-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='hour',
        ),
    ]
