# Generated by Django 4.1.2 on 2022-10-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_superhero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ID',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
    ]
