# Generated by Django 4.1.1 on 2022-10-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_teacherincharge_formationcenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='yearGroup',
        ),
        migrations.AddField(
            model_name='yeargroup',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='base.trainee'),
        ),
        migrations.AlterField(
            model_name='formationcenter',
            name='teacherInCharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formationCenter', to='base.teacherincharge'),
        ),
    ]
