# Generated by Django 4.1.2 on 2022-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_deadline_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
