# Generated by Django 4.1.2 on 2022-10-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_id_user_first_name_remove_user_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='last_name',
        ),
    ]
