# Generated by Django 4.1.1 on 2022-11-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_deadline_date_alter_interview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='base.mentor')),
                ('teacherInCharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherInCharge', to='base.teacherincharge')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='base.trainee')),
            ],
        ),
    ]
