# Generated by Django 4.1.1 on 2022-10-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_deadline_user_enum_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
