# Generated by Django 4.1.1 on 2022-11-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_tutorteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorteam',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorTeam', to='base.mentor'),
        ),
        migrations.AlterField(
            model_name='tutorteam',
            name='teacherInCharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorTeam', to='base.teacherincharge'),
        ),
        migrations.AlterField(
            model_name='tutorteam',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorTeam', to='base.trainee'),
        ),
    ]
