# Generated by Django 4.1.1 on 2022-11-14 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_tutorteam_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationcenter',
            name='teacherInCharge',
        ),
        migrations.RemoveField(
            model_name='yeargroup',
            name='semester',
        ),
        migrations.AddField(
            model_name='teacherincharge',
            name='formationCenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherInCharge', to='base.formationcenter'),
        ),
        migrations.AddField(
            model_name='yeargroup',
            name='beginDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
