# Generated by Django 4.1.1 on 2022-11-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_formationcenter_teacherincharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='base.company'),
        ),
    ]
