# Generated by Django 4.1.1 on 2022-11-14 13:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_remove_company_mentor_mentor_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('formationCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='base.formationcenter')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('authentication.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Trainee',
            new_name='Apprentice',
        ),
        migrations.RenameField(
            model_name='tutorteam',
            old_name='trainee',
            new_name='apprentice',
        ),
        migrations.RenameField(
            model_name='yeargroup',
            old_name='trainee',
            new_name='apprentice',
        ),
        migrations.RemoveField(
            model_name='tutorteam',
            name='teacherInCharge',
        ),
        migrations.DeleteModel(
            name='TeacherInCharge',
        ),
        migrations.AddField(
            model_name='tutorteam',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorTeam', to='base.tutor'),
        ),
    ]
