FROM sonarqube:latest

#VOLUME /opt/sonarqube/data/web/deploy/plugins/
#RUN mkdir /opt/sonarqube/data/web/deploy/plugins/css
#COPY docker/dev/sonarqube/css /opt/sonarqube/data/web/deploy/plugins/css/

#WORKDIR /opt/sonarqube

#FROM alpine:3.14
#RUN apk add --no-cache git python3 py-pip bash shellcheck 'nodejs>12' openjdk11-jre curl musl-locales musl-locales-lang && \
#apk add --update nodejs npm && \
#apk add --update npm && \
#npm install --silent --save-dev -g typescript css sass python
